from code import interact
import sys
sys.path.append(r'C:\Users\Wcy34\Documents\Github\RT-CLI')

from rt_cli.builder.builder import init_construct_env

env = init_construct_env()
env.DefineGroup('test', None, None)

